# Einleitung 

Bereits 1935 wurden in der damaligen SIA 112 Anforderungen an die Durchbiegung von Stahlbetonbauteilen gestellt. Seither wurde die Gebrauchstauglichkeit, insbesondere die Verformungen von Tragwerken, zu einer zentralen Bemessungsgrösse. Trotz dieser elementaren Rolle im Bemessungsablauf werden Verformungen im Stahlbetonbau in der heutigen Baupraxis häufig nur mit groben Abschätzungen bewertet. Solche Ansätze können zu ungenauen Prognosen führen, die sowohl die Sicherheit als auch die Wirtschaftlichkeit von Bauprojekten beeinträchtigen. Detaillierte Verformungsberechnungen sind in vielen modernen Statiksoftwares implementiert und frei anwendbar. Die theoretischen Hintergründe sind jedoch selten geläufig, und die Tools werden meist als *"Blackbox"* behandelt.

Das Ziel dieser Arbeitsserie, bestehend aus dem Vertiefungsmodul I @gitz_ansatze_2024, Vertiefungsmodul II und der Masterthesis, ist es daher, dem Leser mechanische Modelle zur Bestimmung von Verformungen umfassend aufzuzeigen. In der Vorarbeit @gitz_ansatze_2024 wurden die mechanischen Modelle detailliert beschrieben und anhand von experimentellen Versuchen verifiziert, wobei mehrheitlich auf den Einsatz kommerzieller Finite-Elemente-Tools (FE-Tools) verzichtet wurde. Der Fokus dieser Arbeit liegt nun auf der Integration von FE-Tools mit den theoretischen Grundlagen, um praktisch anwendbare Lösungen zu entwickeln. Verwendet wird hierbei die 3D Statiksoftware AxisVM-X7 und RFEM-6, sowie die 2D Detailstatiksoftware IDEAStatiCa. Sämtliche Analysen beziehen sich auf Stabtragwerke.

Diese Arbeit lässt sich in drei Kernthemen unterteilen. Zuerst wird die Modellvorstellung zur numerischen Integration kinematischer Grössen (primär Krümmung und Schiebung) beschrieben und anhand eines Einführungsbeispiels veranschaulicht, um die theoretischen Grundlagen klar darzustellen. Anschliessend wird die Modellvorstellung an den bereits gut verstandenen Versuchen aus dem Vertiefungsmodul I verifiziert, um die Zuverlässigkeit und Genauigkeit des Modells zu bestätigen. Abschliessend wird die Anwendung an einem vorgespannten Träger demonstriert, um die praktische Relevanz und Anwendbarkeit des entwickelten Modells zu zeigen. Die Arbeit wird mit einem Fazit abgeschlossen, das eine differenzierte Betrachtung zwischen Rückblick und Ausblick bietet und damit sowohl die erreichten Ergebnisse zusammenfasst als auch Erweiterungen aufzeigt.

Durch diese strukturierte Herangehensweise soll ein tieferes Verständnis für das komplexe Tragverhalten von Stahlbetontragwerken geschaffen werden. Zudem soll eine zuverlässige Grundlage zur praktischen Anwendung im konstruktiven Ingenieurbau gelegt werden.